name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: cache
      with:
        path: .deps/chached
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('Cargo.lock') }}
    - name: deps
      if: steps.cache.outputs.cache-hit != 'true'
      run: ./deps.sh
    - name: build
      run: ./build.sh
