name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    
    # setup supported languages

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.5'
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.4'
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - uses: actions/setup-node@v1
      with:
        node-version: '12.13.1'

    # install npm packages if not cached
    - uses: actions/cache@v1
      id: cache-npm
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: deps-npm
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm install
    
    # install python packages if not cached
    - uses: actions/cache@v1
      id: cache-python
      with:
        path: ~/.local/lib/python3.7/site-packages
        key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}
    - name: deps-python
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: sudo apt-get install python3-setuptools && python3 -m pip install --user wheel && python3 -m pip install --user -r requirements.txt

    # build
    - name: build
      run: ./build.sh
